-- Custom types
create type public.app_permission as enum ('appointment.delete', 'appointment.create','appointment.update','appointment.view');
create type public.app_role as enum ('appointment.admin','appointment.approve_level_1','appointment.approve_level_2', 'appointment.moderator','appointment.participant');

-- USER ROLES
create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references public.profiles on delete cascade not null,
  role      app_role not null,
  unique (user_id, role)
);
comment on table public.user_roles is 'Application roles for each user.';

-- ROLE PERMISSIONS
create table public.role_permissions (
  id           bigint generated by default as identity primary key,
  role         app_role not null,
  permission   app_permission not null,
  unique (role, permission)
);
comment on table public.role_permissions is 'Application permissions for each role.';